---
# filename: roles/php5-fpm/tasks/configure.yml
 - name: create haproxy config 
   template: src="www.conf.j2" dest="{{ php5['config']['cnfpath'] }}" mode=0644
   notify: 
    - restart php5-fpm service